### ISSUE TITLE
关于一个fd是否推荐在多个service中可写

### ISSUE THREAD

**Issue by OpenGamex** [cloudwu/skynet_package#4]
目前只在一个service中读，但由于有client.push的需求，所以想在多个service可以直接push, 这样需要在每个服务都subscribe, 像这种需求是否有推荐更好的做法？

**Comment by cloudwu** [comment]
fd 可以在多个 service 中写，这没有问题。注意每个写都是个原子操作，如果你需要写一坨数据的话，不要分开调用多次写就好了。
