### ISSUE TITLE
关于网络异常检测的问题

### ISSUE THREAD

**Issue by OpenGamex** [cloudwu/skynet_package#5]
在局域网中测试，发现客户端禁用网络后重连，服务器无法检测网络断线造成每次重连只有等到TIMEOUT后才行.

**Comment by gjy1606** [comment]
这个其实是有做处理的,但是要你自己加,你在 socket_proxy.lua 里的 proxy.read(fd) 加个 pcall

**Comment by gjy1606** [comment]
`function proxy.read(fd)
    local ok,msg,sz = pcall(skynet.rawcall , get_addr(fd), "text", "R")
    if ok then
        return msg,sz
    else
        error "disconnect"
    end
end`

**Comment by gjy1606** [comment]
`function proxy.read(fd)
    local ok,msg,sz = pcall(skynet.rawcall , get_addr(fd), "text", "R")
    if ok then
        return msg,sz
    else
        error "disconnect"
    end
end`

**Comment by OpenGamex** [comment]
目前用的版本已经加了pcall.
