### ISSUE TITLE
缓存的未完整包，在收完之后是不是忘了free？

### ISSUE THREAD

**Issue by EdisonChen1024** [cloudwu/skynet_package#6]
https://github.com/cloudwu/skynet_package/blob/master/service_package.c#L228

**Comment by cloudwu** [comment]
it's a feature. 不放心可以自己写 test case .  

https://www.chiark.greenend.org.uk/~sgtatham/bugs.html

**Comment by EdisonChen1024** [comment]
*  感谢回复。
*  推荐文章已学习。
*  不过看起来，我这个反馈还是符合规范的啊。我怀疑malloc之后没有free，然后指明是[哪里的malloc](https://github.com/cloudwu/skynet_package/blob/master/service_package.c#L228)。
*  今天又折腾了一下，强行把它free了，结果Segmentation fault:astonished:
仔细看了几回代码才发现，原来queue push的时候只是push了ptr和sz，没有拷贝（我之前看成了是push的时候拷贝了一份），send之后才free的:smile:
