### ISSUE TITLE
关于这种处理方式在cluster模式下的问题

### ISSUE THREAD

**Issue by OpenGamex** [cloudwu/skynet_package#7]
我们的游戏一直都是用这个模式做gate，而且一直都是一台服务器，但由于新的需求需要把gate部分剥离出来，现在有个困扰就是agent部分也要随着gate服务器，但agent中有些游戏逻辑操作，如果把这些游戏逻辑搬到gate感觉有些不妥，如果只是在gate服务器的agent中读取消息再推送的游戏服务器上感觉又和以前的skyent的gate模式一样了。

**Comment by cloudwu** [comment]
不明白这跟 cluster 有什么关系，该怎么用还是怎么用。
